[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
tds_core = { path = "../tds_core" }
tracker = { path = "../tracker" }
tokio = { version = "1.36", features = ["full"] }
sha1 = "0.10"
bytes = "1.5"
hex = "0.4"
